kind: Template
apiVersion: v1
name: allow-5432
description: Permit containers with the net-database-client label to connect to containers with the net-database-server label on port 5432
parameters:
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "acd38d"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-5432
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
    spec:
      podSelector:
        matchLabels:
          connection: net-database-server
      ingress:
      - from:
        - podSelector:
            matchLabels:
              connection: net-database-client
        ports:
        - protocol: TCP
          port: 5432
