kind: Service
apiVersion: v1
metadata:
  annotations:
    description: Service for postgres.
  name: postgres-service
spec:
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  sessionAffinity: None
  type: ClusterIP