kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: gdx-agreements-tracker-api-backend-deployment-configuration
  resourceVersion: "v1.0.0"
  annotations:
    openshift.io/display-name: Deployment GDX agreements tracker API backend configuration.
    description: Deployment for GDX agreements tracker API backend.
    tags: pmo,api,gdx,agreements-tracker,backend

parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "gdx-agreements-tracker"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "api"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "acd38d"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"

  - name: JWKSURI
    displayName: "JWKSURI"
    description: "Keycloak endpoint."
    value: "https://oidc.gov.bc.ca/auth/realms/aaoozhcp/protocol/openid-connect/certs"
  - name: NODE_ENV
    displayName: "NODE_ENV"
    description: "Node environment. [development|production]"
    value: "production"

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: 0-${APP_NAME}-${ROLE_NAME}-env-config
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "Backend API configuration"
      labels:
        name: 0-${APP_NAME}-${ROLE_NAME}-env-config
        app: ${APP_NAME}
        env: ${ENV_NAME}
    type: Opaque
    data:
      JWKSURI: ${JWKSURI}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: ${APP_NAME}-postgres
      CDOGS_CLIENT_ID: ""
      CDOGS_SECRET: ""
      CHES_CLIENT_ID: ""
      CHES_SECRET: ""
      COMMON_COMPONENT_URL: ""
      COMMON_COMPONENT_CHES_API: ""
      COMMON_COMPONENT_CDOGS_API: ""
      COMMON_COMPONENT_TOKEN_HOST: ""
      COMMON_COMPONENT_TOKEN_PATH: ""
