kind: Service
apiVersion: v1
metadata:
  name: app-service
  annotations:
    description: Exposes app to the pods pods.
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP