exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("projects")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("projects").insert([
        {
          id: 1,
          project_number: "0-0",
          project_name: "Octocore",
          version: "CR0-0",
          client_ministry_name: "Energy",
          registration_date: "2019-12-15",
          portfolio_name: "Talae",
          planned_start_date: "2021-03-30",
          fiscal: "16-17",
          planned_end_date: "2014-10-01",
          project_type: "Internal",
          planned_budget: 15499,
          project_status: "Inactive",
          funding: "Combination",
          total_budget: 108150,
          recovery_details: "fully",
          recoverable_total: 52907,
          contract_number: "627439712c37a82a3282d6d1",
          type: "MOU",
          start_date: "2021-10-02",
          date_signed: "2020-07-05",
          end_date: "2018-04-07",
          description:
            "Ad in exercitation cillum enim consequat anim duis irure est in laboris ad.",
        },
        {
          id: 2,
          project_number: "1-1",
          project_name: "Phormula",
          version: "CR1-1",
          client_ministry_name: "Citizens Services",
          registration_date: "2015-11-17",
          portfolio_name: "Zillactic",
          planned_start_date: "2021-06-24",
          fiscal: "15-16",
          planned_end_date: "2019-01-16",
          project_type: "Internal",
          planned_budget: 23868,
          project_status: "Active",
          funding: "Capital",
          total_budget: 104836,
          recovery_details: "fully",
          recoverable_total: 5925,
          contract_number: "627439716410c66886a577e9",
          type: "Other",
          start_date: "2020-10-27",
          date_signed: "2015-02-11",
          end_date: "2020-02-14",
          description: "Aute pariatur labore anim tempor.",
        },
        {
          id: 3,
          project_number: "2-2",
          project_name: "Genmom",
          version: "CR2-2",
          client_ministry_name: "Agriculture and Food",
          registration_date: "2016-09-24",
          portfolio_name: "Miracula",
          planned_start_date: "2021-02-05",
          fiscal: "16-17",
          planned_end_date: "2021-03-09",
          project_type: "Internal",
          planned_budget: 31105,
          project_status: "Active",
          funding: "Operational",
          total_budget: 146446,
          recovery_details: "fully",
          recoverable_total: 40489,
          contract_number: "627439716a3005587f484cc7",
          type: "Other",
          start_date: "2018-01-28",
          date_signed: "2017-04-17",
          end_date: "2019-11-05",
          description: "Qui irure nisi pariatur laborum eiusmod esse culpa.",
        },
        {
          id: 4,
          project_number: "3-3",
          project_name: "Affluex",
          version: "CR3-3",
          client_ministry_name: "Finance",
          registration_date: "2019-03-29",
          portfolio_name: "Ecstasia",
          planned_start_date: "2021-09-19",
          fiscal: "19-20",
          planned_end_date: "2019-05-03",
          project_type: "Internal",
          planned_budget: 54839,
          project_status: "Inactive",
          funding: "Operational",
          total_budget: 123873,
          recovery_details: "Partially",
          recoverable_total: 9343,
          contract_number: "6274397199dbfc51af85bdb1",
          type: "Project Charter",
          start_date: "2021-11-16",
          date_signed: "2021-04-19",
          end_date: "2015-11-13",
          description: "Dolore aute dolor ut ex veniam sunt.",
        },
        {
          id: 5,
          project_number: "4-4",
          project_name: "Zensor",
          version: "CR4-4",
          client_ministry_name: "Advanced Education and Skills Training",
          registration_date: "2020-02-26",
          portfolio_name: "Krog",
          planned_start_date: "2018-11-27",
          fiscal: "17-18",
          planned_end_date: "2020-01-03",
          project_type: "Internal",
          planned_budget: 15291,
          project_status: "Inactive",
          funding: "Operational",
          total_budget: 141797,
          recovery_details: "fully",
          recoverable_total: 37662,
          contract_number: "62743971fb8edb2ca643495e",
          type: "MOU",
          start_date: "2021-04-11",
          date_signed: "2020-11-13",
          end_date: "2021-05-07",
          description: "Labore est sit enim consectetur.",
        },
      ]);
    });
};
