export const rows = [
  {
    lastName: "James",
    firstName: "Fred",
    jobTitle: "Sr. Developer",
    MinistryId: "AEST",
    Notes: "",
    id: 1,
  },
  {
    lastName: "Jascob",
    firstName: "Sierra",
    jobTitle: "Scrum Master",
    MinistryId: "AEST",
    Notes: "",
    id: 2,
  },
  {
    lastName: "Jackie",
    firstName: "Frank",
    jobTitle: "Product Owner",
    MinistryId: "CITZ",
    Notes: "",
    id: 3,
  },
  {
    lastName: "Jefferson",
    firstName: "James",
    jobTitle: "UX Designer",
    MinistryId: "CITZ",
    Notes: "",
    id: 4,
  },
  {
    lastName: "John",
    firstName: "Marston",
    jobTitle: "Director",
    MinistryId: "TRAN",
    Notes: "",
    id: 5,
  },
];
