import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GDX Agreements Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Main</h1>
        <div>
          <h1>Home</h1>
          <Link href="/project">
            <a>test</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <h1>footer</h1>
      </footer>
    </div>
  );
}
