apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app: gdx-agreements
    env: tools
  name: api-build-pipeline
spec:
  finally:
    - name: push-to-teams-success
      params:
        - name: webhook-url
          value: gitops-value
        - name: webhook-payload
          value: |-
            {
                "@type": "MessageCard",
                "@context": "https://schema.org/extensions",
                "summary": "Issue 176715375",
                "themeColor": "33cc33",
                "title": "[DESCW] GDX Agreements Tracker API ",
                "sections": [
                    {
                        "text": "The latest version of GDX Agreements Tracker api has been build and deployed to **dev**."
                    }
                ],
            }
      taskRef:
        kind: Task
        name: teams-notifier

  tasks:
    - name: build-api-builder
      params:
        - name: SCRIPT
          value: |
            oc project
      taskRef:
        kind: ClusterTask
        name: openshift-client
