apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: api-build-trigger-binding
spec:
  params:
    - name: branchName
      value: $(body.ref)
    - name: repoUrl
      value: $(body.repository.url)
