#!/bin/sh -e
#
# S2I run script for the 'lighttpd-centos7' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#
echo 'Starting migrations' >&2;
echo $(npx knex migrate:latest) >&2
echo 'Performing basic seeds' >&2;
echo $(npx knex seed:run --specific '01_capabilities.js') >&2
echo $(npx knex seed:run --specific '02_role_capabilities.js') >&2
echo npx $(knex seed:run --specific '08_picker_options.js') >&2
echo npx $(knex seed:run --specific '09_form_layouts.js') >&2
echo 'Starting up node server' >&2;
exec node src/server.js
