#!/bin/sh -e
#
# S2I run script for the 'lighttpd-centos7' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

echo "Running migration $(npx knex migrate:latest)" >&2
echo "seed:run 08_picker_options.js $(npx knex seed:run --specific '08_picker_options.js')" >&2
echo 'Starting node server' >&2;
exec node src/server.js
