kind: CronJob
apiVersion: batch/v1
metadata:
  annotations:
    description: >-
      CronJob to update the current fiscal year in the gdx-agreements-tracker
      database
    openshift.io/display-name: Cron job template for fiscal year update.
    tags: "pmo,postgres,gdx-agreements-tracker,fiscal"
  resourceVersion: "9243634906"
  name: update-current-year-cron
  uid: 3de28c56-9c37-4f0e-8af0-f53d6b8fb1c6
  creationTimestamp: "2024-03-01T19:38:21Z"
  generation: 9
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: batch/v1
      time: "2024-03-01T19:58:18Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:description": {}
            "f:openshift.io/display-name": {}
            "f:tags": {}
          "f:labels":
            .: {}
            "f:cronjob": {}
            "f:template": {}
        "f:spec":
          "f:concurrencyPolicy": {}
          "f:failedJobsHistoryLimit": {}
          "f:jobTemplate":
            "f:metadata":
              "f:labels":
                .: {}
                "f:cronjob": {}
                "f:template": {}
            "f:spec":
              "f:template":
                "f:spec":
                  "f:containers":
                    'k:{"name":"postgres-current-year-updater"}':
                      "f:image": {}
                      "f:volumeMounts":
                        .: {}
                        'k:{"mountPath":"/backup.conf"}':
                          .: {}
                          "f:mountPath": {}
                          "f:name": {}
                          "f:subPath": {}
                        'k:{"mountPath":"/backups/"}':
                          .: {}
                          "f:mountPath": {}
                          "f:name": {}
                        'k:{"mountPath":"/var/lib/pgsql/data"}':
                          .: {}
                          "f:mountPath": {}
                          "f:name": {}
                      "f:terminationMessagePolicy": {}
                      .: {}
                      "f:resources": {}
                      "f:args": {}
                      "f:env":
                        .: {}
                        'k:{"name":"DATABASE_HOST"}':
                          .: {}
                          "f:name": {}
                          "f:valueFrom":
                            .: {}
                            "f:configMapKeyRef": {}
                        'k:{"name":"DATABASE_NAME"}':
                          .: {}
                          "f:name": {}
                          "f:valueFrom":
                            .: {}
                            "f:configMapKeyRef": {}
                        'k:{"name":"DATABASE_PASSWORD"}':
                          .: {}
                          "f:name": {}
                          "f:valueFrom":
                            .: {}
                            "f:secretKeyRef": {}
                        'k:{"name":"DATABASE_USER"}':
                          .: {}
                          "f:name": {}
                          "f:valueFrom":
                            .: {}
                            "f:configMapKeyRef": {}
                      "f:terminationMessagePath": {}
                      "f:imagePullPolicy": {}
                      "f:name": {}
                  "f:dnsPolicy": {}
                  "f:restartPolicy": {}
                  "f:schedulerName": {}
                  "f:securityContext": {}
                  "f:terminationGracePeriodSeconds": {}
                  "f:volumes":
                    .: {}
                    'k:{"name":"backup-config"}':
                      .: {}
                      "f:configMap":
                        .: {}
                        "f:defaultMode": {}
                        "f:items": {}
                        "f:name": {}
                      "f:name": {}
                    'k:{"name":"backup-db"}':
                      .: {}
                      "f:name": {}
                      "f:persistentVolumeClaim":
                        .: {}
                        "f:claimName": {}
                    'k:{"name":"backup-verification"}':
                      .: {}
                      "f:name": {}
                      "f:persistentVolumeClaim":
                        .: {}
                        "f:claimName": {}
          "f:schedule": {}
          "f:successfulJobsHistoryLimit": {}
          "f:suspend": {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: batch/v1
      time: "2024-03-01T20:15:14Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:status":
          "f:lastScheduleTime": {}
          "f:lastSuccessfulTime": {}
      subresource: status
  namespace: acd38d-dev
  labels:
    cronjob: postgres-cron-current-year
    template: postgres-cron-current-year-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        cronjob: postgres-cron-current_year
        template: postgres-cron-current_year-cronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: backup-db
              persistentVolumeClaim:
                claimName: pmo-backup-db
            - name: backup-verification
              persistentVolumeClaim:
                claimName: pmo-backup-verification
            - name: backup-config
              configMap:
                name: pmo-backup-config-m6mk9gf2bh
                items:
                  - key: backup.conf
                    path: backup.conf
                defaultMode: 420
          containers:
            - resources: {}
              terminationMessagePath: /dev/termination-log
              name: postgres-current-year-updater
              env:
                - name: DATABASE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: pmo-config-ddg76ttmch
                      key: POSTGRES_HOST
                - name: DATABASE_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: pmo-config-ddg76ttmch
                      key: POSTGRES_DB
                - name: DATABASE_USER
                  valueFrom:
                    configMapKeyRef:
                      name: pmo-config-ddg76ttmch
                      key: POSTGRES_USER
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pmo-secrets-7f57hmd56g
                      key: POSTGRES_PASSWORD
              imagePullPolicy: Always
              volumeMounts:
                - name: backup-db
                  mountPath: /backups/
                - name: backup-verification
                  mountPath: /var/lib/pgsql/data
                - name: backup-config
                  mountPath: /backup.conf
                  subPath: backup.conf
              terminationMessagePolicy: File
              image: >-
                image-registry.openshift-image-registry.svc:5000/acd38d-tools/gdx-agreements-tracker-backup-container:latest
              args:
                - /bin/bash
                - "-c"
                - >
                  psql
                  "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST/$DATABASE_NAME"
                  <<EOF

                  DO \$\$ DECLARE
                      current_fiscal VARCHAR(5);
                      current_year INTEGER;
                      next_year INTEGER;
                      next_fiscal VARCHAR(5);
                  BEGIN
                      -- Get the current fiscal year
                      SELECT fiscal_year INTO current_fiscal FROM data.fiscal_year WHERE is_current = true;
                      -- Calculate the next fiscal year
                      current_year := CAST(SPLIT_PART(current_fiscal, '-', 2) AS INTEGER);
                      next_year := current_year + 1;
                      next_fiscal := CONCAT(RIGHT(current_year::TEXT, 2), '-', RIGHT(next_year::TEXT, 2));
                      -- Update is_current for the next fiscal year
                      UPDATE data.fiscal_year SET is_current = false;
                      UPDATE data.fiscal_year SET is_current = true WHERE fiscal_year = next_fiscal;
                      -- TESTING ONLY! Set the fiscal_year back to '22-23' again (testing purposes only)
                      IF NOT EXISTS (SELECT 1 FROM data.fiscal_year WHERE is_current = true) THEN
                      UPDATE data.fiscal_year SET is_current=true WHERE fiscal_year='22-23';
                      END IF;
                  END \$\$;

                  SELECT * FROM data.fiscal_year ORDER BY id ASC;

                  EOF
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
status:
  lastScheduleTime: "2024-03-01T20:15:00Z"
  lastSuccessfulTime: "2024-03-01T20:15:14Z"
