# this is used to create a cronjob that will run a backup of the database
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-fiscal-year-job
  annotations:
    openshift.io/display-name: Cron job template for fiscal year update
    description: CronJob to update the current fiscal year in the gdx-agreements-tracker database
    tags: pmo,postgres,bdx-agreements-tracker,fiscal-year-update
  labels:
    template: "postgres-cron-cronjob"
    cronjob: "postgres-cron-fiscal-update"
spec:
  #schedule: "30 22 31 3 *" # 11:30pm March 31, Annually
  schedule: "*/45 * * * *" # every 10 minutes (for testing "hello world i'm updating the fiscal year")
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
    labels:
      template: "postgres-cron-cronjob"
      cronjob: "postgres-cron-fiscal-update"
    spec:
      template:
        metadata:
          labels:
            template: "postgres-cron-cronjob"
            cronjob: "postgres-cron-fiscal-update"
        spec:
          containers:
            - name: postgres-restore-runner
              image: "bcgovgdx/gdx-agreements-tracker-backup-container"
              command:
                - /bin/bash
                - "-c"
                - >-
                  psql
                  "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST/$DATABASE_NAME"
                  -c 'SELECT * FROM data.fiscal_year;'
              volumeMounts:
                - name: backup-db
                  mountPath: /backups/
                - name: backup-verification
                  mountPath: /var/lib/pgsql/data
                - name: backup-config
                  mountPath: /backup.conf
                  subPath: backup.conf
              env:
                - name: DATABASE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: pmo-config-ddg76ttmch
                      key: POSTGRES_HOST
                - name: BACKUP_STRATEGY
                  value: rolling
                - name: BACKUP_DIR
                  valueFrom:
                    configMapKeyRef:
                      name: backup-config
                      key: BACKUP_DIR
                - name: MONTHLY_BACKUPS
                  value: "3"
                - name: DATABASE_USER
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: POSTGRES_USER
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: POSTGRES_PASSWORD
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: config
                      key: POSTGRES_DB
          volumes:
            - name: backup-db
              persistentVolumeClaim:
                claimName: backup-db
            - name: backup-verification
              persistentVolumeClaim:
                claimName: backup-verification
            - name: backup-config
              configMap:
                name: backup-config
                items:
                  - key: backup.conf
                    path: backup.conf
                    # make sure all these configKeyRefs are correct
          dnsPolicy: "ClusterFirst"
          successfulJobHistoryLimit: 5
          failedJobHistoryLimit: 2
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 1600
          serviceAccountName: "default"
          serviceAccount: "default"
