name: Build Nginx Image.
on:
  push:
    branches: 
      - development
    paths:
      - "openshift/templates/nginx-runtime/**/*"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  deploy:
    if: github.repository_owner == 'bcgov'
    runs-on: ubuntu-latest
    steps:
      - name: Image Build for gdx-agreements-tracker-app-nginx-runtime
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL }}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project acd38d-tools
            oc start-build gdx-agreements-tracker-app-nginx-runtime --follow
