name: Check frontend package version was updated
on:
  pull_request:
      branches:
          - development
      paths:
          - 'frontend/**'
          - 'backend/**'
jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check frontend package.json changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr diff ${{ github.event.pull_request.number }} --name-only | grep frontend/package.json -c
