FROM nginx:1-alpine

COPY tail_* /usr/bin
COPY docker-entrypoint.sh /

RUN chmod +x /usr/bin/tail_*.sh /docker-entrypoint.sh ;\
    apk add --no-cache curl bash ;\
    apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main fcgiwrap spawn-fcgi

CMD [""]
ENTRYPOINT ["/docker-entrypoint.sh"]

